openapi: 3.0.0
info:
  title: Check Service API
  description: Provides the status of your services
  version: "1.0.0"
  contact:
    email: ctang93@my.bcit.ca
paths:
  /check:
    get:
      operationId: app.get_checks
      responses:
        "200":
          description: OK - stats returned
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Check"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  
  /stats:
    get:
      summary: Get the event stats
      operationId: app.get_event_stats
      description: Retrieve statistics for all events
      responses:
        '200':
          description: Successfully returned the event stats
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Stats'
components:
  schemas:
    Check:
      required:
        - receiver
        - storage
        - processing
        - analyzer
      properties:
        receiver:
          type: string
          example: "Healthy"
        storage:
          type: string
          example: "Storage has 6 BP and 4 HR events"
        processing:
          type: string
          example: "Processing has 6 BP and 4 HR events"
        analyzer:
          type: string
          example: "Analyzer has 10 BP and 4 HR events"
    Stats:
      required:
        - num_reviews
        - num_ratings
        - thumbs_up_count
        - thumbs_down_count
        - last_updated
      properties:
        num_reviews:
          type: integer
          example: 500
        num_ratings:
          type: integer
          example: 300
        thumbs_up_count:
          type: integer
          example: 250
        thumbs_down_count:
          type: integer
          example: 50
        last_updated:
          type: string
          format: date-time
          example: '2024-10-01T12:30:00Z'
