openapi: 3.0.0
info:
  description: This API provides event anomalies
  version: "1.0.0"
  title: Anomaly API
  contact:
    email: ctang93@my.bcit.ca

paths:
  /anomalies:
    get:
      summary: Gets the event anomalies
      operationId: app.get_anomalies
      description: Gets the list of event anomalies from newest to oldest
      parameters:
        - name: anomaly_type
          in: query
          description: The type of anomaly to retrieve
          schema:
            type: string
            enum: ["TooHigh", "TooLow", "Too Short", "Too Long", "Low Rating", "High Rating"]
            example: TooHigh
        - name: event_type
          in: query
          description: The type of event to retrieve
          required: false
          schema:
            type: string
            enum: ["get_all_reviews", "rating_game"]
      responses:
        '200':
          description: Successfully returned a list of anomalies of the given type
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Anomaly'
        '400':
          description: Invalid Anomaly Type
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: Anomalies do not exist
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

components:
  schemas:
    Anomaly:
      required:
      - event_id
      - trace_id
      - event_type
      - anomaly_type
      - description
      - timestamp
      properties:
        event_id:
          type: string
          example: A1234
        trace_id:
          type: string
          example: 12345
        event_type:
          type: string
          example: EVENT1
        anomaly_type:
          type: string
          example: Too High
        description:
          type: string
          example: The value is too high
        timestamp:
          type: string
          format: date-time
          example: 2024-01-01T00:00:00Z
      type: object

